SOURCE_PATH = "test_source_code"
NS_PKG_1_NAME = "ns_pkg_1"
NS_PKG_2_NAME = "ns_pkg_2"
NAMESPACE_PKG = "namespacepkg"
TP_PKG = "third_party_import_pkg"
OTHER_PKG = "other_package"
LOCAL_PACKAGE = "local_package"
IMPORT_LOCAL_DEPS_PKG = "import_local_deps"
